Use pointers to nested variant errors to avoid compilation errors
Should fix https://github.com/NordSecurity/uniffi-bindgen-go/issues/36

Definitely fixes an issue I've been having where the given test case fails
with:
```
generated/errors/errors.go:1399:12: cannot use FfiConverterTypeValidationErrorINSTANCE.Read(reader) (value of type error) as ValidationError value in struct literal: need type assertion
generated/errors/errors.go:1410:57: cannot use variantValue.Source (variable of type ValidationError) as *ValidationError value in argument to FfiConverterTypeValidationErrorINSTANCE.Write
```

This seems to be because the code sometimes expected `*ValidationError` and sometimes `ValidationError`.
This patch makes the code use `*ValidationError` everywhere.

Tests should hopefully prove they don't nil deference.

Signed-off-by: Kegan Dougal <7190048+kegsay@users.noreply.github.com>